package br.com.redesurftank.havalshisuku.models

enum class SharedPreferencesKeys(val key: String, val description: String) {
    DISABLE_MONITORING("disableMonitoring", "Manter desativado monitoramento de distrações"),
    CLOSE_WINDOW_ON_POWER_OFF("closeWindowOnPowerOff", "Fechar janela ao desligar o veículo"),
    SET_STARTUP_VOLUME("setStartupVolume", "Definir volume ao ligar o veículo"),
    STARTUP_VOLUME("startupVolume", "Volume ao ligar o veículo"),
    CLOSE_WINDOWS_ON_SPEED("closeWindowsOnSpeed", "Fechar janelas ao atingir velocidade"),
    SPEED_THRESHOLD("speedThreshold", "Velocidade limite para fechar janelas"),
    NIGHT_START_HOUR("nightStartHour", "Hora de início da noite"),
    NIGHT_START_MINUTE("nightStartMinute", "Minuto de início da noite"),
    NIGHT_END_HOUR("nightEndHour", "Hora de fim da noite"),
    NIGHT_END_MINUTE("nightEndMinute", "Minuto de fim da noite"),
    ENABLE_AUTO_BRIGHTNESS("enableAutoBrightness", "Habilitar ajuste automático de brilho"),
    ENABLE_FRIDA_HOOKS("enableFridaHooks", "Habilitar hooks do Frida"),
    ENABLE_FRIDA_HOOK_SYSTEM_SERVER("enableFridaHookSystemServer", "Habilitar hooks do Frida no System Server"),
    ENABLE_INSTRUMENT_PROJECTOR("enableInstrumentProjector", "Habilitar dados no painel de instrumentos"),
    ENABLE_INSTRUMENT_REVISION_WARNING("enableInstrumentRevisionWarning", "Habilitar aviso de revisão no painel de instrumentos"),
    INSTRUMENT_REVISION_KM("instrumentRevisionKm", "Quilometragem para aviso de revisão no painel de instrumentos"),
    INSTRUMENT_REVISION_NEXT_DATE("instrumentRevisionNextDate", "Data da próxima revisão no painel de instrumentos"),
    DISABLE_AVAS("disableAvas", "Desativar AVAS (sistema de alerta de veículo silencioso)"),
    DISABLE_AVM_CAR_STOPPED("disableAvmCarStopped", "Desativar camera AVM quando o carro está parado"),
    CAR_MONITOR_PROPERTIES("carMonitorProperties", "Propriedades do monitoramento do carro"),
    BYPASS_SELF_INSTALLATION_INTEGRITY_CHECK("bypassSelfInstallationIntegrityCheck", "Ignorar verificação de integridade da instalação"),
    SELF_INSTALLATION_INTEGRITY_CHECK("selfInstallationIntegrityCheck", "Verificação de integridade da instalação"),
    ADVANCE_USE("advanceUse", "Uso avançado"),
    CURRENT_USER("currentUser", "Usuário atual"),
    CAR_SETTINGS_PREFIX("carSettings_", "Configurações do carro"),
}